import type { Profile, DmMessageWithProfile } from "./supabase/types";

export const FAKE_USERS: Profile[] = [
  {
    id: "fake-user-1",
    username: "marcus_johnson",
    display_name: "Marcus Johnson",
    avatar_url: null,
    intercom_id: null,
    bio: "Worship leader for 12 years. MultiTracks has completely transformed our Sunday experience. Always looking to connect with other worship creatives.",
    location: "Nashville, TN",
    job_title: "Worship Leader",
    created_at: "2024-03-10T10:00:00Z",
    role: "member",
    is_banned: false,
    muted_until: null,
    admin_note: null,
    mt_account_link: "https://multitracks.com/user/marcus_johnson",
  },
  {
    id: "fake-user-2",
    username: "sarah_mitchell",
    display_name: "Sarah Mitchell",
    avatar_url: null,
    intercom_id: null,
    bio: "Keys and vocals at Cornerstone Church. MultiTracks stems have been a game changer for our production quality.",
    location: "Atlanta, GA",
    job_title: "Keys / Vocalist",
    created_at: "2024-04-02T10:00:00Z",
    role: "member",
    is_banned: false,
    muted_until: null,
    admin_note: null,
    mt_account_link: "https://multitracks.com/user/sarah_mitchell",
  },
  {
    id: "fake-user-3",
    username: "jake_rivera",
    display_name: "Jake Rivera",
    avatar_url: null,
    intercom_id: null,
    bio: "Drummer and percussionist. Lover of click tracks and tight low end. Playing at Mosaic Dallas.",
    location: "Dallas, TX",
    job_title: "Drummer / Percussionist",
    created_at: "2024-02-20T10:00:00Z",
    role: "member",
    is_banned: false,
    muted_until: null,
    admin_note: null,
    mt_account_link: "https://multitracks.com/user/jake_rivera",
  },
  {
    id: "fake-user-4",
    username: "amy_chen",
    display_name: "Amy Chen",
    avatar_url: null,
    intercom_id: null,
    bio: "Lead vocalist and worship artist. Passionate about creating space for authentic worship.",
    location: "Los Angeles, CA",
    job_title: "Lead Vocalist",
    created_at: "2024-05-01T10:00:00Z",
    role: "member",
    is_banned: false,
    muted_until: null,
    admin_note: null,
    mt_account_link: "https://multitracks.com/user/amy_chen",
  },
  {
    id: "fake-user-5",
    username: "david_thompson",
    display_name: "David Thompson",
    avatar_url: null,
    intercom_id: null,
    bio: "Lead guitarist at Elevation Church Charlotte. Gear nerd and tone chaser.",
    location: "Charlotte, NC",
    job_title: "Lead Guitar",
    created_at: "2024-01-28T10:00:00Z",
    role: "member",
    is_banned: false,
    muted_until: null,
    admin_note: null,
    mt_account_link: "https://multitracks.com/user/david_t",
  },
  {
    id: "fake-user-6",
    username: "lisa_anderson",
    display_name: "Lisa Anderson",
    avatar_url: null,
    intercom_id: null,
    bio: "Music director overseeing a team of 30 musicians. MultiTracks chart builder saves us hours every week.",
    location: "Chicago, IL",
    job_title: "Music Director",
    created_at: "2024-03-15T10:00:00Z",
    role: "member",
    is_banned: false,
    muted_until: null,
    admin_note: null,
    mt_account_link: "https://multitracks.com/user/lisa_anderson",
  },
  {
    id: "fake-user-7",
    username: "chris_martinez",
    display_name: "Chris Martinez",
    avatar_url: null,
    intercom_id: null,
    bio: "Bass player at Lakewood Houston. Love the low end. MultiTracks bass stems are world-class.",
    location: "Houston, TX",
    job_title: "Bass Guitar",
    created_at: "2024-02-05T10:00:00Z",
    role: "member",
    is_banned: false,
    muted_until: null,
    admin_note: null,
    mt_account_link: "https://multitracks.com/user/chris_m",
  },
];

function ago(days: number, hours = 0, minutes = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(d.getHours() - hours);
  d.setMinutes(d.getMinutes() - minutes);
  return d.toISOString();
}

const PREVIEW_PROFILE = {
  id: "preview-user-id",
  username: "you",
  display_name: "You",
  avatar_url: null,
  intercom_id: null,
  bio: null,
  location: null,
  job_title: null,
  created_at: "",
  role: "admin",
  is_banned: false,
  muted_until: null,
  admin_note: null,
  mt_account_link: null,
};

function msg(id: string, sender: Profile, content: string, created_at: string): DmMessageWithProfile {
  return {
    id,
    thread_id: `fake-thread-${sender.id === "preview-user-id" ? "you" : sender.id}`,
    sender_id: sender.id,
    content,
    attachment_url: null,
    created_at,
    profiles: sender,
  };
}

export const FAKE_DM_CONVERSATIONS: Record<string, DmMessageWithProfile[]> = {
  "fake-user-1": [
    msg("f1-1", FAKE_USERS[0], "Hey! Just finished building out our set for Sunday — using the MultiTracks stems for 'Graves Into Gardens' and the mix is incredible.", ago(2, 3)),
    msg("f1-2", PREVIEW_PROFILE, "Awesome! Are you running the full stems or the instrumental mix?", ago(2, 3)),
    msg("f1-3", FAKE_USERS[0], "Full stems through Ableton. The drum separation alone is worth it 😄", ago(2, 2, 45)),
    msg("f1-4", FAKE_USERS[0], "Quick question — is there a way to download just the click track separately?", ago(2, 2, 30)),
    msg("f1-5", PREVIEW_PROFILE, "Yes! On the stems page, look for the 'Drums Only' stem — the click is isolated on a mono side channel.", ago(2, 2, 15)),
    msg("f1-6", FAKE_USERS[0], "Perfect, exactly what I needed. Thanks!", ago(2, 2)),
    msg("f1-7", FAKE_USERS[0], "Also — does the chart builder support Nashville number charts? Our pianist reads NNS.", ago(1, 5)),
    msg("f1-8", PREVIEW_PROFILE, "Not yet natively, but it's on the roadmap. I'll flag your request to the product team!", ago(1, 4, 45)),
    msg("f1-9", FAKE_USERS[0], "That would be huge. Appreciate you!", ago(1, 4, 30)),
  ],
  "fake-user-2": [
    msg("f2-1", FAKE_USERS[1], "Hi! I've been using MultiTracks for about 6 months — wanted to share some feedback if that's okay?", ago(3, 1)),
    msg("f2-2", PREVIEW_PROFILE, "Of course, we love hearing from users! What's on your mind?", ago(3, 0, 50)),
    msg("f2-3", FAKE_USERS[1], "I'd love to see more keys patches for some of the older catalog songs. Sometimes the patches feel a bit dated.", ago(3, 0, 40)),
    msg("f2-4", PREVIEW_PROFILE, "That's really useful — I'll pass it to the production team. Are there specific songs you're thinking of?", ago(3, 0, 30)),
    msg("f2-5", FAKE_USERS[1], "Yeah, some of the older Hillsong and Bethel stuff. The newer tracks are 🔥 though.", ago(3, 0, 20)),
    msg("f2-6", FAKE_USERS[1], "Also the new Playback app is a HUGE upgrade. The per-stem mix control is exactly what we needed.", ago(1, 2)),
    msg("f2-7", PREVIEW_PROFILE, "Glad you're loving it! What's your typical band setup?", ago(1, 1, 45)),
    msg("f2-8", FAKE_USERS[1], "5-piece — keys, guitar, bass, drums, and 2 vocalists. We've been on MultiTracks for 3 years. Total game changer for our church.", ago(1, 1, 30)),
  ],
  "fake-user-3": [
    msg("f3-1", FAKE_USERS[2], "Quick question — is the click track on the Elevation songs mono or stereo?", ago(1, 6)),
    msg("f3-2", PREVIEW_PROFILE, "It's mono by default, but you can pan it in the Playback app stem controls.", ago(1, 5, 50)),
    msg("f3-3", FAKE_USERS[2], "That was the issue! The click was bleeding into the main mix. Fixed now. Thanks!", ago(1, 5, 30)),
    msg("f3-4", FAKE_USERS[2], "BTW I'm upgrading my IEM setup soon. Anyone in the community running Aviom or Allen & Heath?", ago(1, 5)),
    msg("f3-5", PREVIEW_PROFILE, "Great question for the #general channel — lots of gear people in there.", ago(1, 4, 45)),
    msg("f3-6", FAKE_USERS[2], "Good call, I'll post there. Appreciate the quick support!", ago(1, 4, 30)),
  ],
  "fake-user-4": [
    msg("f4-1", PREVIEW_PROFILE, "Hey Amy, welcome to the MultiTracks community! 🎉", ago(5, 2)),
    msg("f4-2", FAKE_USERS[3], "Thank you!! So excited to connect with other worship musicians here.", ago(5, 1, 45)),
    msg("f4-3", FAKE_USERS[3], "Quick question — are vocal guides available for all songs in the catalog?", ago(5, 1, 30)),
    msg("f4-4", PREVIEW_PROFILE, "Most of the newer catalog has them! Filter by 'Vocal Guide' in the song search.", ago(5, 1, 15)),
    msg("f4-5", FAKE_USERS[3], "That's so helpful, thank you! We're doing 'Way Maker' this weekend and the vocal harmonies in the stems are perfect.", ago(5, 1)),
    msg("f4-6", PREVIEW_PROFILE, "One of our best-selling tracks! Hope the service goes great 🙏", ago(5, 0, 45)),
    msg("f4-7", FAKE_USERS[3], "It was incredible. The congregation was fully engaged. MultiTracks made the whole thing so smooth.", ago(3, 3)),
  ],
  "fake-user-5": [
    msg("f5-1", FAKE_USERS[4], "Hey — is anyone else having latency issues with the Playback app on older iPads?", ago(2, 8)),
    msg("f5-2", PREVIEW_PROFILE, "Which generation iPad are you on?", ago(2, 7, 50)),
    msg("f5-3", FAKE_USERS[4], "6th gen, iOS 16.4", ago(2, 7, 40)),
    msg("f5-4", PREVIEW_PROFILE, "That should be fully supported. Can you email support@multitracks.com with your device info and we'll dig in?", ago(2, 7, 30)),
    msg("f5-5", FAKE_USERS[4], "Will do. Other than that, absolutely loving the platform.", ago(2, 7, 15)),
    msg("f5-6", FAKE_USERS[4], "The guitar stems on the Maverick City stuff are so well-recorded. Whoever mixed those is a genius 🎸", ago(2, 7)),
    msg("f5-7", PREVIEW_PROFILE, "Couldn't agree more. Those sessions were incredible.", ago(2, 6, 45)),
  ],
  "fake-user-6": [
    msg("f6-1", FAKE_USERS[5], "Wanted to share some feedback on the chart builder — we use it every single week for rehearsals.", ago(4, 1)),
    msg("f6-2", PREVIEW_PROFILE, "Love hearing that! What would make it even better for you?", ago(4, 0, 50)),
    msg("f6-3", FAKE_USERS[5], "A feature to assign instruments to specific chart sections would be huge. E.g. 'guitar enters at bridge'.", ago(4, 0, 40)),
    msg("f6-4", PREVIEW_PROFILE, "That's really smart. Are you using Nashville numbers or standard notation?", ago(4, 0, 30)),
    msg("f6-5", FAKE_USERS[5], "Mix of both depending on the musician. We have classically trained folks and self-taught players on the same team.", ago(4, 0, 20)),
    msg("f6-6", FAKE_USERS[5], "But honestly the chart builder has already saved us hours every week. It's one of our most-used features.", ago(4, 0, 10)),
    msg("f6-7", PREVIEW_PROFILE, "That's amazing to hear! I'll make sure the product team sees this feedback.", ago(4)),
    msg("f6-8", FAKE_USERS[5], "Thank you! Keep up the great work. MultiTracks has genuinely elevated our entire ministry.", ago(3, 8)),
  ],
  "fake-user-7": [
    msg("f7-1", FAKE_USERS[6], "Love the new bass stems on the recent Elevation tracks. The low end sits perfectly.", ago(1, 4)),
    msg("f7-2", PREVIEW_PROFILE, "Great to hear! Do you find yourself eq'ing them much for your setup?", ago(1, 3, 50)),
    msg("f7-3", FAKE_USERS[6], "A little — slight high-pass around 40hz and a gentle boost at 250. But honestly they're pretty much ready to go.", ago(1, 3, 40)),
    msg("f7-4", PREVIEW_PROFILE, "That's exactly the goal. What genres does your church primarily do?", ago(1, 3, 30)),
    msg("f7-5", FAKE_USERS[6], "Mix of contemporary, some gospel, a little hymns reimagined. Big range, which is why MultiTracks is perfect for us.", ago(1, 3, 20)),
    msg("f7-6", FAKE_USERS[6], "The stem flexibility means I can dial in the feel for each style without completely rebuilding the track.", ago(1, 3)),
    msg("f7-7", PREVIEW_PROFILE, "That's what we built it for. Thanks for sharing — enjoy the gig Sunday! 🎸", ago(1, 2, 45)),
  ],
};
